#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eadproject.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable(Table instance);
    partial void UpdateTable(Table instance);
    partial void DeleteTable(Table instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table> Tables
		{
			get
			{
				return this.GetTable<Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Area;
		
		private string _MasjidName;
		
		private string _MasjidAddress;
		
		private string _FajrTime;
		
		private string _ZuhrTime;
		
		private string _AsarTime;
		
		private string _MaghribTime;
		
		private string _EshaTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnMasjidNameChanging(string value);
    partial void OnMasjidNameChanged();
    partial void OnMasjidAddressChanging(string value);
    partial void OnMasjidAddressChanged();
    partial void OnFajrTimeChanging(string value);
    partial void OnFajrTimeChanged();
    partial void OnZuhrTimeChanging(string value);
    partial void OnZuhrTimeChanged();
    partial void OnAsarTimeChanging(string value);
    partial void OnAsarTimeChanged();
    partial void OnMaghribTimeChanging(string value);
    partial void OnMaghribTimeChanged();
    partial void OnEshaTimeChanging(string value);
    partial void OnEshaTimeChanged();
    #endregion
		
		public Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="NChar(100)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasjidName", DbType="NChar(100)")]
		public string MasjidName
		{
			get
			{
				return this._MasjidName;
			}
			set
			{
				if ((this._MasjidName != value))
				{
					this.OnMasjidNameChanging(value);
					this.SendPropertyChanging();
					this._MasjidName = value;
					this.SendPropertyChanged("MasjidName");
					this.OnMasjidNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasjidAddress", DbType="NChar(100)")]
		public string MasjidAddress
		{
			get
			{
				return this._MasjidAddress;
			}
			set
			{
				if ((this._MasjidAddress != value))
				{
					this.OnMasjidAddressChanging(value);
					this.SendPropertyChanging();
					this._MasjidAddress = value;
					this.SendPropertyChanged("MasjidAddress");
					this.OnMasjidAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FajrTime", DbType="NChar(100)")]
		public string FajrTime
		{
			get
			{
				return this._FajrTime;
			}
			set
			{
				if ((this._FajrTime != value))
				{
					this.OnFajrTimeChanging(value);
					this.SendPropertyChanging();
					this._FajrTime = value;
					this.SendPropertyChanged("FajrTime");
					this.OnFajrTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZuhrTime", DbType="NChar(100)")]
		public string ZuhrTime
		{
			get
			{
				return this._ZuhrTime;
			}
			set
			{
				if ((this._ZuhrTime != value))
				{
					this.OnZuhrTimeChanging(value);
					this.SendPropertyChanging();
					this._ZuhrTime = value;
					this.SendPropertyChanged("ZuhrTime");
					this.OnZuhrTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsarTime", DbType="NChar(100)")]
		public string AsarTime
		{
			get
			{
				return this._AsarTime;
			}
			set
			{
				if ((this._AsarTime != value))
				{
					this.OnAsarTimeChanging(value);
					this.SendPropertyChanging();
					this._AsarTime = value;
					this.SendPropertyChanged("AsarTime");
					this.OnAsarTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaghribTime", DbType="NChar(100)")]
		public string MaghribTime
		{
			get
			{
				return this._MaghribTime;
			}
			set
			{
				if ((this._MaghribTime != value))
				{
					this.OnMaghribTimeChanging(value);
					this.SendPropertyChanging();
					this._MaghribTime = value;
					this.SendPropertyChanged("MaghribTime");
					this.OnMaghribTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EshaTime", DbType="NChar(100)")]
		public string EshaTime
		{
			get
			{
				return this._EshaTime;
			}
			set
			{
				if ((this._EshaTime != value))
				{
					this.OnEshaTimeChanging(value);
					this.SendPropertyChanging();
					this._EshaTime = value;
					this.SendPropertyChanged("EshaTime");
					this.OnEshaTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
