<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Area" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="MasjidName" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="MasjidAddress" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="FajrTime" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ZuhrTime" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="AsarTime" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="MaghribTime" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="EshaTime" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>